name: flutter_movies
description: Flutter Movie project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_remote_config: ^3.0.14
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  intl: ^0.17.0
  transparent_image: ^2.0.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
